# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454af7e2e7c4373fb6b965234b0677a278d22f893511f04eccadd7963be5d516520d03ff972af41d48057f907eedf2b930a393038121548356c31e18bd330bfc

test:
  secret_key_base: cc40e698661ba6607895bb334f486aa00ff8938087181518f8697925239a5b733c4cb1035d490139c81066dfbaf1ac2cf283941b6cdb2b2f9c37337b4900b7d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
